version: "3.8"

services:
  todo_db:
    image: postgres:15
    container_name: todo_db
    restart: always
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_pwd
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  todo_api:
    build: ./todo-api
    container_name: todo_api
    restart: always
    depends_on:
      - todo_db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/todo
      SPRING_DATASOURCE_USERNAME: todo_user
      SPRING_DATASOURCE_PASSWORD: todo_pwd

  todo_app:
    build: ./todo-app
    container_name: todo_app
    restart: always
    depends_on:
      - todo_api
    ports:
      - "3000:80"

volumes:
  postgres_data:
